github: ['Ravilea']
patreon: ['Ravilea']
open_collective: ['Ravilea']
ko_fi: ['Ravilea']
tidelift: ['Ravilea']
community_bridge: ['Ravilea']
liberapay: ['Ravilea']
issuehunt: ['Ravilea']
otechie: ['Ravilea']
lfx_crowdfunding: ['Ravilea']
custom: ['https://github.com/Ravilea/Discord-Token-Generator/']
